# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-15 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('birth', models.DateTimeField()),
                ('joinpartytime', models.DateTimeField()),
                ('job', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('education', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('graduationtime', models.DateTimeField()),
                ('phonenumber', models.IntegerField()),
                ('remark', models.CharField(max_length=20)),
            ],
        ),
    ]
